export const RN_STORYBOOK_STORAGE_KEY = 'lastOpenedStory';
export const RN_STORYBOOK_EVENTS = {
  RN_GET_INDEX: 'RN_GET_INDEX',
  RN_GET_INDEX_RESPONSE: 'RN_GET_INDEX_RESPONSE',
};
export const STORYBOOK_STORY_ID_PARAM = 'STORYBOOK_STORY_ID';
