export const mock = {
  v: 4,
  entries: {
    'actionbutton--another-action': {
      type: 'story',
      id: 'actionbutton--another-action',
      name: 'Another Action',
      title: 'ActionButton',
      importPath: './components/ActionExample/Actions.stories.tsx',
      tags: ['story'],
    },
    'actionbutton--basic': {
      type: 'story',
      id: 'actionbutton--basic',
      name: 'Basic',
      title: 'ActionButton',
      importPath: './components/ActionExample/Actions.stories.tsx',
      tags: ['story'],
    },
    'backgroundexample-background-csf--basic': {
      type: 'story',
      id: 'backgroundexample-background-csf--basic',
      name: 'Basic',
      title: 'BackgroundExample/Background CSF',
      importPath: './components/BackgroundExample/BackgroundCsf.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-array-control--basic': {
      type: 'story',
      id: 'controlexamples-array-control--basic',
      name: 'Basic',
      title: 'ControlExamples/Array control',
      importPath: './components/ControlExamples/Array/Array.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-boolean-control--basic': {
      type: 'story',
      id: 'controlexamples-boolean-control--basic',
      name: 'Basic',
      title: 'ControlExamples/Boolean Control',
      importPath: './components/ControlExamples/Boolean/Boolean.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-boolean-control--on': {
      type: 'story',
      id: 'controlexamples-boolean-control--on',
      name: 'On',
      title: 'ControlExamples/Boolean Control',
      importPath: './components/ControlExamples/Boolean/Boolean.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-color-control--color-example': {
      type: 'story',
      id: 'controlexamples-color-control--color-example',
      name: 'Color Example',
      title: 'ControlExamples/Color control',
      importPath: './components/ControlExamples/Color/Color.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-control-example--example': {
      type: 'story',
      id: 'controlexamples-control-example--example',
      name: 'Example',
      title: 'ControlExamples/Control Example',
      importPath: './components/ControlExamples/ControlExample/ControlExample.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-date--basic': {
      type: 'story',
      id: 'controlexamples-date--basic',
      name: 'Basic',
      title: 'ControlExamples/Date',
      importPath: './components/ControlExamples/Date/Date.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-number--basic': {
      type: 'story',
      id: 'controlexamples-number--basic',
      name: 'Basic',
      title: 'ControlExamples/Number',
      importPath: './components/ControlExamples/Number/Number.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-number--range': {
      type: 'story',
      id: 'controlexamples-number--range',
      name: 'Range',
      title: 'ControlExamples/Number',
      importPath: './components/ControlExamples/Number/Number.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-object-control--basic': {
      type: 'story',
      id: 'controlexamples-object-control--basic',
      name: 'Basic',
      title: 'ControlExamples/Object control',
      importPath: './components/ControlExamples/Object/Object.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-radio-control--basic': {
      type: 'story',
      id: 'controlexamples-radio-control--basic',
      name: 'Basic',
      title: 'ControlExamples/Radio control',
      importPath: './components/ControlExamples/Radio/Radio.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-selectwithnumber--basic': {
      type: 'story',
      id: 'controlexamples-selectwithnumber--basic',
      name: 'Basic',
      title: 'ControlExamples/SelectWithNumber',
      importPath: './components/ControlExamples/Reproductions/SelectWithNumber.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-select-control--basic': {
      type: 'story',
      id: 'controlexamples-select-control--basic',
      name: 'Basic',
      title: 'ControlExamples/Select control',
      importPath: './components/ControlExamples/Select/Select.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-select-control--with-labels': {
      type: 'story',
      id: 'controlexamples-select-control--with-labels',
      name: 'With Labels',
      title: 'ControlExamples/Select control',
      importPath: './components/ControlExamples/Select/Select.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-select-control--with-mapping': {
      type: 'story',
      id: 'controlexamples-select-control--with-mapping',
      name: 'With Mapping',
      title: 'ControlExamples/Select control',
      importPath: './components/ControlExamples/Select/Select.stories.tsx',
      tags: ['story'],
    },
    'controlexamples-text-control--basic': {
      type: 'story',
      id: 'controlexamples-text-control--basic',
      name: 'Basic',
      title: 'ControlExamples/Text control',
      importPath: './components/ControlExamples/Text/Text.stories.tsx',
      tags: ['story'],
    },
    'textinput--basic': {
      type: 'story',
      id: 'textinput--basic',
      name: 'Basic',
      title: 'TextInput',
      importPath: './components/InputExample/TextInput.stories.tsx',
      tags: ['story'],
    },
    'interaction-example--scrolling': {
      type: 'story',
      id: 'interaction-example--scrolling',
      name: 'Scrolling',
      title: 'Interaction Example',
      importPath: './components/InteractionExample/InteractionExample.stories.tsx',
      tags: ['story'],
    },
    'interaction-example--static': {
      type: 'story',
      id: 'interaction-example--static',
      name: 'Static',
      title: 'Interaction Example',
      importPath: './components/InteractionExample/InteractionExample.stories.tsx',
      tags: ['story'],
    },
    'interaction-example--touchable': {
      type: 'story',
      id: 'interaction-example--touchable',
      name: 'Touchable',
      title: 'Interaction Example',
      importPath: './components/InteractionExample/InteractionExample.stories.tsx',
      tags: ['story'],
    },
    'nestingexample-message--message-first': {
      type: 'story',
      id: 'nestingexample-message--message-first',
      name: 'Message First',
      title: 'NestingExample/Message',
      importPath: './components/NestingExample/ChatMessage.stories.tsx',
      tags: ['story'],
    },
    'nestingexample-message--message-second': {
      type: 'story',
      id: 'nestingexample-message--message-second',
      name: 'Message Second',
      title: 'NestingExample/Message',
      importPath: './components/NestingExample/ChatMessage.stories.tsx',
      tags: ['story'],
    },
    'nestingexample-message-bubble--first': {
      type: 'story',
      id: 'nestingexample-message-bubble--first',
      name: 'First',
      title: 'NestingExample/Message/bubble',
      importPath: './components/NestingExample/ChatMessageBubble.stories.tsx',
      tags: ['story'],
    },
    'nestingexample-message-bubble--second': {
      type: 'story',
      id: 'nestingexample-message-bubble--second',
      name: 'Second',
      title: 'NestingExample/Message/bubble',
      importPath: './components/NestingExample/ChatMessageBubble.stories.tsx',
      tags: ['story'],
    },
    'nestingexample-message-bubble-a-very-long-name-for-a-title-that-just-keeps-going-and-going--first':
      {
        type: 'story',
        id: 'nestingexample-message-bubble-a-very-long-name-for-a-title-that-just-keeps-going-and-going--first',
        name: 'First',
        title:
          'NestingExample/Message/bubble/a very long name for a title that just keeps going and going',
        importPath: './components/NestingExample/ChatMessageBubbleAgain.stories.tsx',
        tags: ['story'],
      },
    'nestingexample-message-bubble-a-very-long-name-for-a-title-that-just-keeps-going-and-going--second':
      {
        type: 'story',
        id: 'nestingexample-message-bubble-a-very-long-name-for-a-title-that-just-keeps-going-and-going--second',
        name: 'Second',
        title:
          'NestingExample/Message/bubble/a very long name for a title that just keeps going and going',
        importPath: './components/NestingExample/ChatMessageBubbleAgain.stories.tsx',
        tags: ['story'],
      },
    'nestingexample-messageinput--basic': {
      type: 'story',
      id: 'nestingexample-messageinput--basic',
      name: 'Basic',
      title: 'NestingExample/MessageInput',
      importPath: './components/NestingExample/ChatMessageMessageInput.stories.tsx',
      tags: ['story'],
    },
    'nestingexample-message-reactions--message-one': {
      type: 'story',
      id: 'nestingexample-message-reactions--message-one',
      name: 'Message One',
      title: 'NestingExample/Message/Reactions',
      importPath: './components/NestingExample/ChatMessageReactions.stories.tsx',
      tags: ['story'],
    },
    'nestingexample-message-reactions--message-two': {
      type: 'story',
      id: 'nestingexample-message-reactions--message-two',
      name: 'Message Two',
      title: 'NestingExample/Message/Reactions',
      importPath: './components/NestingExample/ChatMessageReactions.stories.tsx',
      tags: ['story'],
    },
    'notes-example--notes-example': {
      type: 'story',
      id: 'notes-example--notes-example',
      name: 'Notes Example',
      title: 'Notes example',
      importPath: './components/NotesExample/NotesExample.stories.tsx',
      tags: ['story'],
    },
    'safeareaexamples-inside-safearea--basic': {
      type: 'story',
      id: 'safeareaexamples-inside-safearea--basic',
      name: 'Basic',
      title: 'SafeAreaExamples/Inside SafeArea',
      importPath: './components/SafeAreaExample/SafeAreaInside.stories.tsx',
      tags: ['story'],
    },
    'safeareaexamples-inside-safearea--list-basic': {
      type: 'story',
      id: 'safeareaexamples-inside-safearea--list-basic',
      name: 'List Basic',
      title: 'SafeAreaExamples/Inside SafeArea',
      importPath: './components/SafeAreaExample/SafeAreaInside.stories.tsx',
      tags: ['story'],
    },
    'safeareaexamples-outside-safearea--basic': {
      type: 'story',
      id: 'safeareaexamples-outside-safearea--basic',
      name: 'Basic',
      title: 'SafeAreaExamples/Outside SafeArea',
      importPath: './components/SafeAreaExample/SafeAreaOutside.stories.tsx',
      tags: ['story'],
    },
    'safeareaexamples-outside-safearea--list-basic': {
      type: 'story',
      id: 'safeareaexamples-outside-safearea--list-basic',
      name: 'List Basic',
      title: 'SafeAreaExamples/Outside SafeArea',
      importPath: './components/SafeAreaExample/SafeAreaOutside.stories.tsx',
      tags: ['story'],
    },
    'safeareaexamples-usable-area--no-safe-area': {
      type: 'story',
      id: 'safeareaexamples-usable-area--no-safe-area',
      name: 'No Safe Area',
      title: 'SafeAreaExamples/Usable Area',
      importPath: './components/SafeAreaExample/UsableArea.stories.tsx',
      tags: ['story'],
    },
    'safeareaexamples-usable-area--safe-area': {
      type: 'story',
      id: 'safeareaexamples-usable-area--safe-area',
      name: 'Safe Area',
      title: 'SafeAreaExamples/Usable Area',
      importPath: './components/SafeAreaExample/UsableArea.stories.tsx',
      tags: ['story'],
    },
    'ui-button--active': {
      type: 'story',
      id: 'ui-button--active',
      name: 'Active',
      title: 'UI/Button',
      importPath: '../../packages/react-native-ui/src/Button.stories.tsx',
      tags: ['story'],
    },
    'ui-button--animated': {
      type: 'story',
      id: 'ui-button--animated',
      name: 'Animated',
      title: 'UI/Button',
      importPath: '../../packages/react-native-ui/src/Button.stories.tsx',
      tags: ['story'],
    },
    'ui-button--base': {
      type: 'story',
      id: 'ui-button--base',
      name: 'Base',
      title: 'UI/Button',
      importPath: '../../packages/react-native-ui/src/Button.stories.tsx',
      tags: ['story'],
    },
    'ui-button--disabled': {
      type: 'story',
      id: 'ui-button--disabled',
      name: 'Disabled',
      title: 'UI/Button',
      importPath: '../../packages/react-native-ui/src/Button.stories.tsx',
      tags: ['story'],
    },
    'ui-button--icon-only': {
      type: 'story',
      id: 'ui-button--icon-only',
      name: 'Icon Only',
      title: 'UI/Button',
      importPath: '../../packages/react-native-ui/src/Button.stories.tsx',
      tags: ['story'],
    },
    'ui-button--sizes': {
      type: 'story',
      id: 'ui-button--sizes',
      name: 'Sizes',
      title: 'UI/Button',
      importPath: '../../packages/react-native-ui/src/Button.stories.tsx',
      tags: ['story'],
    },
    'ui-button--variants': {
      type: 'story',
      id: 'ui-button--variants',
      name: 'Variants',
      title: 'UI/Button',
      importPath: '../../packages/react-native-ui/src/Button.stories.tsx',
      tags: ['story'],
    },
    'ui-button--with-icon': {
      type: 'story',
      id: 'ui-button--with-icon',
      name: 'With Icon',
      title: 'UI/Button',
      importPath: '../../packages/react-native-ui/src/Button.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-explorer--simple': {
      type: 'story',
      id: 'ui-sidebar-explorer--simple',
      name: 'Simple',
      title: 'UI/Sidebar/Explorer',
      importPath: '../../packages/react-native-ui/src/Explorer.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-tree--dark': {
      type: 'story',
      id: 'ui-sidebar-tree--dark',
      name: 'Dark',
      title: 'UI/Sidebar/Tree',
      importPath: '../../packages/react-native-ui/src/Tree.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-tree--full': {
      type: 'story',
      id: 'ui-sidebar-tree--full',
      name: 'Full',
      title: 'UI/Sidebar/Tree',
      importPath: '../../packages/react-native-ui/src/Tree.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-tree--single-story-components': {
      type: 'story',
      id: 'ui-sidebar-tree--single-story-components',
      name: 'Single Story Components',
      title: 'UI/Sidebar/Tree',
      importPath: '../../packages/react-native-ui/src/Tree.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-treenode--expandable': {
      type: 'story',
      id: 'ui-sidebar-treenode--expandable',
      name: 'Expandable',
      title: 'UI/Sidebar/TreeNode',
      importPath: '../../packages/react-native-ui/src/TreeNode.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-treenode--expandable-long-name': {
      type: 'story',
      id: 'ui-sidebar-treenode--expandable-long-name',
      name: 'Expandable Long Name',
      title: 'UI/Sidebar/TreeNode',
      importPath: '../../packages/react-native-ui/src/TreeNode.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-treenode--nested': {
      type: 'story',
      id: 'ui-sidebar-treenode--nested',
      name: 'Nested',
      title: 'UI/Sidebar/TreeNode',
      importPath: '../../packages/react-native-ui/src/TreeNode.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-treenode--selection': {
      type: 'story',
      id: 'ui-sidebar-treenode--selection',
      name: 'Selection',
      title: 'UI/Sidebar/TreeNode',
      importPath: '../../packages/react-native-ui/src/TreeNode.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-treenode--selection-with-long-name': {
      type: 'story',
      id: 'ui-sidebar-treenode--selection-with-long-name',
      name: 'Selection With Long Name',
      title: 'UI/Sidebar/TreeNode',
      importPath: '../../packages/react-native-ui/src/TreeNode.stories.tsx',
      tags: ['story'],
    },
    'ui-sidebar-treenode--types': {
      type: 'story',
      id: 'ui-sidebar-treenode--types',
      name: 'Types',
      title: 'UI/Sidebar/TreeNode',
      importPath: '../../packages/react-native-ui/src/TreeNode.stories.tsx',
      tags: ['story'],
    },
    'othercomponents-testcase1--basic': {
      type: 'story',
      id: 'othercomponents-testcase1--basic',
      name: 'Basic',
      title: 'OtherComponents/TestCase1',
      importPath: './other_components/TestCase/TestCase.stories.tsx',
      tags: ['story'],
    },
    'othercomponents-testcase2--basic': {
      type: 'story',
      id: 'othercomponents-testcase2--basic',
      name: 'Basic',
      title: 'OtherComponents/TestCase2',
      importPath: './other_components/TestCase2/TestCase2.stories.tsx',
      tags: ['story'],
    },
  },
};
