module.exports = {
  globals: {
    __TRANSFORM_HTML__: true,
  },
  cacheDirectory: '.cache/jest',
  clearMocks: true,
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/fileMock.js',
    '\\.(css|scss)$': '<rootDir>/__mocks__/styleMock.js',
    '\\.(md)$': '<rootDir>/__mocks__/htmlMock.js',
    '^riot$': 'riot/riot',
  },
  roots: [
    // '<rootDir>/addons',
    '<rootDir>/app',
    '<rootDir>/lib',
    // '<rootDir>/examples/cra-kitchen-sink',
    // '<rootDir>/examples/vue-kitchen-sink',
    // '<rootDir>/examples/svelte-kitchen-sink',
    // '<rootDir>/examples/riot-kitchen-sink',
    // '<rootDir>/examples/html-kitchen-sink',
    // '<rootDir>/examples/official-storybook',
    // '<rootDir>/examples/ember-cli',
    // '<rootDir>/examples/angular-cli',
  ],
  snapshotSerializers: ['@emotion/snapshot-serializer'],
  transform: {
    '^.+\\.jsx?$': '<rootDir>/scripts/babel-jest.js',
    '^.+[/\\\\].storybook[/\\\\]config\\.ts$': '<rootDir>/scripts/jest-ts-babel.js',
    '^.+\\.(ts|html)$': '<rootDir>/node_modules/jest-preset-angular/preprocessor.js',
    '.*\\.(vue)$': '<rootDir>/node_modules/jest-vue-preprocessor',
    '.*\\.(svelte)$': '<rootDir>/node_modules/svelte-jest',
    '^.+\\.(tag)$': '<rootDir>/node_modules/riot-jest-transformer',
    '^.+\\.(txt)$': '<rootDir>/node_modules/jest-raw-loader',
  },
  testPathIgnorePatterns: ['/node_modules/', '/dist/', 'addon-jest.test.js', '/cli/test/'],
  collectCoverage: true,
  collectCoverageFrom: [
    'app/**/*.{js,jsx}',
    'lib/**/*.{js,jsx}',
    'addons/**/*.{js,jsx}',
    '!**/cli/test/**',
    '!**/dist/**',
    '!**/generators/**',
  ],
  coverageDirectory: 'coverage',
  testEnvironment: 'jsdom',
  setupTestFrameworkScriptFile: './scripts/jest.init.js',
  setupFiles: ['raf/polyfill'],
  testURL: 'http://localhost',
  modulePathIgnorePatterns: ['/dist/.*/__mocks__/'],
  moduleFileExtensions: [
    'ts',
    'tsx',
    'js',
    'jsx',
    'json',
    'node',
    '.html',
    '.svelte',
    'vue',
    'tag',
  ],
};
