packages:
  - 'packages/*'
  - 'examples/*'
  - 'docs'
  - 'tests'
linkWorkspacePackages: true
ignoreScripts: true
nodeLinker: hoisted
shamefullyHoist: true
minimumReleaseAge: 1340
overrides:
  '@types/markdown-it': ^14.0.1
  '@babel/plugin-transform-modules-systemjs': 7.29.4
  '@tootallnate/once': 3.0.1
  '@xmldom/xmldom': 0.8.13
  fast-uri: 3.1.2
  fast-xml-builder: 1.2.0
  fast-xml-parser: 5.7.2
  follow-redirects: 1.16.0
  jest-environment-jsdom>jsdom: 26.1.0
  lodash: ^4.18.1
  markdown-it: ^14.0.0
  minimatch@3: ~3.1.3
  postcss: 8.5.14
  react-native-safe-area-context: 5.8.0
  react-docgen-typescript: 2.2.2
  serialize-javascript: 7.0.5
  shell-quote: 1.8.4
  svgo: 3.3.3
  webpack-dev-server: ^5.2.2
  zod-validation-error: ^4.0.0
