/* do not change this file, it is auto generated by storybook. */
/// <reference types="@storybook/react-native/metro-env" />
import { start, updateView, type View, type Features } from '@storybook/react-native';


import "@storybook/addon-ondevice-controls/register";
import "@storybook/addon-ondevice-actions/register";
import "@storybook/addon-ondevice-notes/register";
import "storybook-addon-deep-controls/register";

const normalizedStories = [
  {
    titlePrefix: "",
    directory: "../expo-example/components",
    files: "**/*.stories.?(ts|tsx|js|jsx)",
    importPathMatcher: /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/,
    req: require.context(
      '../../expo-example/components',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:ts|tsx|js|jsx)?)$/
    ),
  }
];


declare global {
  var view: View;
  var STORIES: typeof normalizedStories;
  var STORYBOOK_WEBSOCKET:
    | { host?: string; port?: number; secured?: boolean }
    | undefined;
  var FEATURES: Features;
}


const annotations = [
  require('./preview'),
  require("@storybook/react-native/preview"),
  require('storybook-addon-deep-controls/preview')
];

globalThis.STORIES = normalizedStories;
globalThis.STORYBOOK_WEBSOCKET = {
  host: '192.168.1.225',
  port: 7007,
  secured: false,
};

module?.hot?.accept?.();

globalThis.FEATURES.ondeviceBackgrounds = true;

const options = {}

if (!globalThis.view) {
  globalThis.view = start({
    annotations,
    storyEntries: normalizedStories,
    options,
  });
} else {
  updateView(globalThis.view, annotations, normalizedStories, options);
}

export const view: View = globalThis.view;
