package OpenSourceProjects_Storybook.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '1ea2b5bd-28f6-44f5-8ab3-6c659ce8fbd6' (id = 'OpenSourceProjects_Storybook_SmokeTests')
accordingly and delete the patch script.
*/
changeBuildType("1ea2b5bd-28f6-44f5-8ab3-6c659ce8fbd6") {
    expectSteps {
        script {
            name = "Bootstrap"
            scriptContent = """
                yarn
                yarn bootstrap --core
            """.trimIndent()
            dockerImage = "node:latest"
        }
        script {
            name = "CRA"
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                cd examples/cra-kitchen-sink
                yarn storybook --smoke-test
            """.trimIndent()
            dockerImage = "node:latest"
        }
        script {
            name = "Vue"
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                cd examples/vue-kitchen-sink
                yarn storybook --smoke-test
            """.trimIndent()
            dockerImage = "node:latest"
        }
        script {
            name = "Angular"
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                cd examples/angular-cli
                yarn storybook --smoke-test
            """.trimIndent()
            dockerImage = "node:latest"
        }
        script {
            name = "Polymer"
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                cd examples/polymer-cli
                yarn storybook --smoke-test
            """.trimIndent()
            dockerImage = "node:latest"
        }
        script {
            name = "Mithril"
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                cd examples/mithril-kitchen-sink
                yarn storybook --smoke-test
            """.trimIndent()
            dockerImage = "node:latest"
        }
        script {
            name = "HTML"
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                cd examples/html-kitchen-sink
                yarn storybook --smoke-test
            """.trimIndent()
            dockerImage = "node:latest"
        }
        script {
            name = "Marko"
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                cd examples/marko-cli
                yarn storybook --smoke-test
            """.trimIndent()
            dockerImage = "node:latest"
        }
        script {
            name = "official-storybook"
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                cd examples/official-storybook
                yarn storybook --smoke-test
            """.trimIndent()
            dockerImage = "node:latest"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            dockerImage = "node:%docker.node.version%"
        }
    }
}
