package OpenSourceProjects_Storybook.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'b1db1a3a-a4cf-46ea-8f55-98b86611f92e' (id = 'OpenSourceProjects_Storybook_CliTest')
accordingly, and delete the patch script.
*/
changeBuildType("b1db1a3a-a4cf-46ea-8f55-98b86611f92e") {
    expectSteps {
        script {
            name = "Test"
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                yarn
                yarn test --cli --teamcity
            """.trimIndent()
            dockerImage = "node:%docker.node.version%"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            scriptContent = """
                #!/bin/sh
                
                set -e -x
                
                yarn
                rm -rf addons/actions/node_modules/@storybook
                yarn test --cli --teamcity
            """.trimIndent()
        }
    }
}
