export const theme = {
  backgroundColor: 'white',
  storyListBackgroundColor: '#f6f9fc',
  listItemTextColor: '#444444',
  listItemActiveColor: '#1ea7fd',
  listItemActiveTextColor: 'white',
  sectionActiveColor: '#e0ebf5',
  headerTextColor: 'black',
  labelColor: 'black',
  borderColor: '#e6e6e6',
  previewBorderColor: '#b3b3b3',
  buttonTextColor: '#999999',
  buttonActiveTextColor: '#444444',
  secondaryLabelColor: '#999999',
};
