package OpenSourceProjects_Storybook.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = 'f0bd8d49-0f6a-4859-9d26-d066af4b5d6d' (id = 'OpenSourceProjects_Storybook_SBNext')
in the project with uuid = '69382d9b-7791-418a-9ff6-1c83b86ed6b5' and delete the patch script.
*/
create("69382d9b-7791-418a-9ff6-1c83b86ed6b5", GitVcsRoot({
    uuid = "f0bd8d49-0f6a-4859-9d26-d066af4b5d6d"
    id = "OpenSourceProjects_Storybook_SBNext"
    name = "SBNext"
    url = "https://github.com/storybooks/SBNext"
    authMethod = password {
        userName = "Hypnosphi"
        password = "credentialsJSON:5ffe2d7e-531e-4f6f-b1fc-a41bfea26eaa"
    }
}))

