package OpenSourceProjects_Storybook.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '69382d9b-7791-418a-9ff6-1c83b86ed6b5' (id = 'OpenSourceProjects_Storybook')
accordingly and delete the patch script.
*/
changeProject("69382d9b-7791-418a-9ff6-1c83b86ed6b5") {
    features {
        add {
            feature {
                type = "Invitation"
                id = "PROJECT_EXT_209"
                param("createdByUserId", "1702")
                param("invitationType", "joinProjectInvitation")
                param("secure:token", "credentialsJSON:07400f1b-a51d-46ae-b056-2e24a653f4d1")
                param("name", "Join Storybook project")
                param("welcomeText", "Filipp Riabchun invites you to join the Storybook project")
                param("disabled", "false")
                param("groupKey", "STORYBOOK_DEVELO")
                param("multi", "true")
            }
        }
    }
}
