name: Checks

on:
  push:
    branches:
      - next
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Check everything!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: install and compile
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build
      - name: lint
        run: pnpm lint
      - name: format check
        run: pnpm format:check
      - name: type check example
        run: pnpm --filter expo-example check
      - name: test
        run: pnpm test:ci
